### ISSUE TITLE
Feature request: Ask before expense deletion (see #106)

### ISSUE THREAD

**Issue by shynst** [spliit-app/spliit#102]
An expense can be easily deleted: Click on "Edit" followed by "Delete" and it is gone for good:

```ts
async function deleteExpenseAction() {
  'use server'
  await deleteExpense(expenseId)
  redirect(`/groups/${groupId}`)
}
```

I think that's too easy. Mistakes can (and will...) happen! We should at least pop up a dialog and ask for confirmation. This is what I expect when clicking on a red button!

I personally like the idea that groups cannot be removed from the UI. How about applying this concept to expenses, too? Rather than actually removing them from the database just flag them as deleted.

**Comment by Gukkey** [comment]
Right now @scastiel has not given his inputs on #106, so I have added a PR that adheres only to this issue. Once @scastiel gives his input on #106 I will add further commits that with either resolve #106 too or won't impact any PRs that are made for that issue.

**Comment by shynst** [comment]
Thank you @Gukkey for taking action. Your dialog looks fine!
