### ISSUE TITLE
Feature request: transaction log (see #106)

### ISSUE THREAD

**Issue by shynst** [spliit-app/spliit#103]
Writing on #102 brings to my mind another concern:

It's not that I don't trust the people I share the expenses with, but imagine a scenario where someone changes the amount of some transactions way back in the past. Not only deletion could be a problem but also changes might stay undiscovered and could be a source of discussion. Who changed what, why?

I know, having a full fledged history with rollback would be nice (see #15) but for now having a simple transaction log stored in the database would be enough.

I'm thinking of a table `TransactionLog` with 4 columns: `expenseId`, `timestamp`, `user`, `message`

**Comment by Gukkey** [comment]
Hi @shynst @scastiel I would like to work on this issue but might need some suggestions. Transaction logs would be much better if they were separate for each group since having one transaction log as a whole would be messy since each group might have different people.

**Comment by shynst** [comment]
Actually this is superseded by #106 which solves this issue too! So I am closing this issue.
