### ISSUE TITLE
Feature Request : Whiteboard in Group similar to splitwise

### ISSUE THREAD

**Issue by Nova-Spectre** [spliit-app/spliit#108]
Needed Whiteboard to display important information, like address or emergency contact info.   whiteboard will visible to anyone who join group

**Comment by Gukkey** [comment]
Hi, when you mean whiteboard here do you mean something like a notes section or an actual whiteboard where you can scribble freely?

**Comment by Nova-Spectre** [comment]
Yes , something like notes where user can mention some important details

**Comment by danipj** [comment]
could this be something like group description?
