### ISSUE TITLE
Wrong Calculation

### ISSUE THREAD

**Issue by Anspik** [spliit-app/spliit#109]
As shown below, In image 1 we can see Jhon payed for all 3 $60, 
so,

Jane -Owns 20 to Jhon
Jack - Owns 20 to Jhon

after that Jane paid 120 for Jane and Jack
Jack - owns 60 to jane

So,
Jack owns 40 to jane
Jack owns 20 to Jhon

But in Balance tab it shows
Jack owes John  |  $ 40.00
Jack owes Jane  |  $ 40.00

![image](https://github.com/spliit-app/spliit/assets/160846703/3c518d80-bbbe-450d-b90d-f5b983b03078)
![image](https://github.com/spliit-app/spliit/assets/160846703/2a1001c0-e033-4f07-a450-004cc9238ed8)

**Comment by Anspik** [comment]
the correct distribution should be 
Jack owns 
      60 to Jane
      20 to John

Jane Owns
      20 to Jhon

**Comment by shynst** [comment]
The calculation is correct!

| | John | Jane | Jack |
| -- | -- | -- | -- |
| Money | 40 | -20 | -20 |
| Food | 0 | 60 | -60 |
| **Balances** | **40** | **40** | **-80** |

**Comment by Anspik** [comment]
@shynst but jack should not own 40 to john

**Comment by shynst** [comment]
@scastiel this can be used as a good example to explain how depts are simplified.

**Comment by Anspik** [comment]
Closing this issue.
