### ISSUE TITLE
Feature request: Add notes to expenses

### ISSUE THREAD

**Issue by shynst** [spliit-app/spliit#110]
Personally I don't need to attach images or documents to an expense (at least not until now). However, being able to add textual notes/comments to each expense would be great.

**Comment by manuerwin** [comment]
Fantastic, very much agree !!

**Comment by Big-Hammer** [comment]
New user here, first time with Spliit as I'm looking for a Splitwise replacement. I do like what I see so far in Spliit and the facility to add a small note to an expense would be welcome. 
Splitting the costs of a group road trip mean that expenses will be incurred over quite a long period of time so recording some commentary is always good when we come to look at the expenses weeks or months later and wonder WTF "Food" was and why only 2 out of the 3 group members are tagged in it.
