### ISSUE TITLE
[Bug] Invoice scanning - wrong amount in preview

### ISSUE THREAD

**Issue by webzit** [spliit-app/spliit#121]
When scanning an invoice, an incorrect amount is displayed in the preview, although the correct amount is entered in the field.

![standard-rechnung-beispiel-1024x540](https://github.com/spliit-app/spliit/assets/79612125/2c0c2013-898a-481f-806d-df7c38d4fa78)
<img width="517" alt="Bildschirmfoto 2024-03-03 um 13 12 21" src="https://github.com/spliit-app/spliit/assets/79612125/c8eef118-530b-4e36-9df6-3f6411e831d7">
<img width="752" alt="Bildschirmfoto 2024-03-03 um 13 12 31" src="https://github.com/spliit-app/spliit/assets/79612125/66f30975-3d40-42ee-9ef8-a3de6a96cc95">

**Comment by justcallmelarry** [comment]
Looks like a duplicate of https://github.com/spliit-app/spliit/issues/87, unless I'm missing something

**Comment by webzit** [comment]
Apologies, I overlooked that. Close in favour of #87
