### ISSUE TITLE
Bug: expenses with a future date mistakenly shown as "earlier this month"

### ISSUE THREAD

**Issue by jantuomi** [spliit-app/spliit#130]
## Observed

See image. An expense with the date "Mar 25, 2024" is shown in the "earlier this month" segment (current date at time of screenshot: Mar 13, 2024).  The ordering of the expense dates is also wrong as Mar 25 is shown between Mar 13 and Mar 8. 

<img width="707" alt="Screenshot 2024-03-13 at 21 02 26" src="https://github.com/spliit-app/spliit/assets/5064726/e8cfa23f-92ad-4ec1-bfda-cd314a2c744a">

## Expected

Future dates would have a separate "Coming up"/"Soon"/"Future expenses"/etc segment that would be visually above "This week".

## Use case

It can make sense to set the date of bank transfers, invoices or other scheduled payments to match their due date, which is most of the time a future date.

## Fix

I can probably fix this one myself. Haven't looked into the date logic yet but I don't think there are technical blockers.

**Comment by justcallmelarry** [comment]
That one should have been fixed by https://github.com/spliit-app/spliit/pull/122

Is the code you are running up to date? (Asking since I believe you are self hosting, maybe even from your own fork)

**Comment by jantuomi** [comment]
Ah, that’s good! My instance is not that fresh 😁 I’ll close this issue as obsolete.13.3.2024 22:17、Lauri Vuorela ***@***.***>のメール:﻿
That one should have been fixed by #122
Is the code you are running up to date? (Asking since I believe you are self hosting, maybe even from your own fork)
