### ISSUE TITLE
Support: Visible transactions amounts per person

### ISSUE THREAD

**Issue by vvnwng** [spliit-app/spliit#131]
The transaction only shows the full amount and doesn't show how much of each transaction is allocated to each person. 

Is there a way for me to see the amounts that the transaction has split out into? Maybe I just can't find where it is?

Thanks!

**Comment by manuerwin** [comment]
Very much agree, I've been meaning to ask the same thing for awhile, for example the following is much easier to understand :)
<img width="529" alt="image" src="https://github.com/spliit-app/spliit/assets/982158/b442b8f8-b168-4811-857a-7012abe7dfc4">

**Comment by ChristopherJohnston** [comment]
This could probably be incorporated into the expense summary in place of "Participant A Paid for Participant B, Participant C":

<img width="744" alt="image" src="https://github.com/spliit-app/spliit/assets/3932568/86285564-4820-4886-ace3-f64022488b54">
