### ISSUE TITLE
Mark as paid selects the wrong participant

### ISSUE THREAD

**Issue by brabidou** [spliit-app/spliit#133]
When using the Mark as paid link on the balances screen, it does not auto select the correct paid by user. It appears to select the current user. 

If the Active user is set to none the correct participant is selected.

Steps to reproduce.

1. Open a group with unpaid recipients
2. Under settings make sure the active user is set to someone other than the participant who will be reimbursed. Do not use None.
3. Under the Balances Page select the "Mark as paid" link
5. The paid by participant will default to the active user.

**Comment by sahilmhr** [comment]
Hi I am fixed this issue and raised PR #134 . Please check

**Comment by ChristopherJohnston** [comment]
looks like the PR to fix this was merged so the issue can be closed
