### ISSUE TITLE
Add titles to "buttons" for a better user experience

### ISSUE THREAD

**Issue by magomzr** [spliit-app/spliit#135]
In the "expenses" section there is only a title for the middle button (which is actually a button) with the message "Create expense from receipt". However, the two side buttons (which are anchor tags) do not indicate what action they perform or what they are for.

HTML anchor tags also have the "title" property.

Actual:
![no-title](https://github.com/spliit-app/spliit/assets/60667991/6f36b44a-4a45-4316-a376-f5cd7a4cc28e)

Expected, better UX experience:
![export](https://github.com/spliit-app/spliit/assets/60667991/0ebf4a9f-96ed-47cd-a0e1-bf83bcf8ec4e)

**Comment by ChristopherJohnston** [comment]
Hi @magomzr - thanks for raising the issue. Please feel free to submit a PR with this improvement!

**Comment by magomzr** [comment]
Thanks @ChristopherJohnston, I'm on it. I created the issue to link it
