### ISSUE TITLE
Wrong path with deploy in apache2 with subfolder - Help

### ISSUE THREAD

**Issue by Maxco10** [spliit-app/spliit#145]
Hi,

I have an apache2 server with this schema:

- www:
- - spliit (nodejs)
- -other project( php,ts, ect..)

In apache's configuration, I used a proxy as 

ProxyPass /spliit/ http://localhost:3001/
ProxyPassReverse /spliit/ http://localhost:3001/

when I navigate to the page, I see the spliit project without css, js and all ref with a wrong pointing. It seems, spliit project is working only if it is on root of server.

I suppose that the nextJS is using the routing in a wrong way. 

Any idea? Are there people with my same issue?

**Comment by ChristopherJohnston** [comment]
Try setting the base path in tsconfig.json

https://nextjs.org/docs/app/api-reference/next-config-js/basePath

**Comment by Maxco10** [comment]
I just tried but it is not working. Any idea?
