### ISSUE TITLE
Default Split

### ISSUE THREAD

**Issue by truedem0n** [spliit-app/spliit#148]
Add a feature to set defaults for split. I don't like to define the share each time I enter an expense.

**Comment by justcallmelarry** [comment]
I don't understand, is the current setting not enough? If not, could you elaborate on what your issue with the default split is?

<img width="614" alt="image" src="https://github.com/spliit-app/spliit/assets/24991021/c852ab17-10a0-4c54-9773-80ef0a140f35">

**Comment by GAZ082** [comment]
Yeah, its already there. What you do need to do is to define it one per device (browse and mobile for example). This issue can be closed.
