### ISSUE TITLE
Pull access denied for spliit2 when attempting to run in a container

### ISSUE THREAD

**Issue by lokesh-krishna** [spliit-app/spliit#151]
Was following the instructions to run in a container and running `npm run start-container` results in the following error: 
```
Error response from daemon: pull access denied for spliit2, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
What am I missing?

**Comment by actuallyrisk** [comment]
i think there is something misconfigured, i have the same problem

**Comment by xaquib666** [comment]
same issue. what is wrong?

**Comment by justcallmelarry** [comment]
It sounds like you have not run `npm run build-image` before running `npm run start-container` (as per the instructions [here](https://github.com/spliit-app/spliit?tab=readme-ov-file#run-in-a-container))

**Comment by xaquib666** [comment]
> It sounds like you have not run `npm run build-image` before running `npm run start-container` (as per the instructions [here](https://github.com/spliit-app/spliit?tab=readme-ov-file#run-in-a-container))
> 
> There is currently no image published anywhere (AFAIK) that you could pull

Thanks! Now it works!

**Comment by justcallmelarry** [comment]
> Tried this but I get an `unknown shorthand flag: 't' in -t` when I run `npm run build-image`

OK, maybe you need to upgrade your docker installation or similar, not sure exactly in what verison it was added, but you can find the documentation [here](https://docs.docker.com/reference/cli/docker/buildx/build/)

**Comment by lokesh-krishna** [comment]
Turns out I was missing docker-buildx. Sorry for the noise!
