### ISSUE TITLE
How to add translations?

### ISSUE THREAD

**Issue by victormihalache** [spliit-app/spliit#192]
Seeing as 1.9.0 now supports i18n, would adding a translation be as trivial as adding a file for the respective language in `src/messages`?

**Comment by bitgroestl** [comment]
You also need to add your locale (the filename in `src/messages` without the file extension) here: https://github.com/spliit-app/spliit/blob/5dfe03b3f11e16e16355e65ef092da77715b4bd1/src/i18n.ts#L4. Besides this it's really that trivial
