### ISSUE TITLE
Warning stays when it shouldn't

### ISSUE THREAD

**Issue by bitgroestl** [spliit-app/spliit#198]
## How to reproduce
- Create or edit an expense (or just go [here](https://spliit.app/groups/CsQk_POWhH6X17lJU0O86/expenses/mL2gO2lLUhbkyYJCLWAG7/edit))
- In the "Paid for"-section, click on "Select none".
  - A warning appears ("The expense must be paid for at least one participant."). This is expected.
- In the "Paid for"-section, select one or more users.
- The warning stays.

## Problem
After selecting a user, the warning should disappear (even if the "Select none"-button was used previously)

**Comment by scastiel** [comment]
Fixed in #210
