### ISSUE TITLE
Expenses are being multiplied by 100

### ISSUE THREAD

**Issue by SethGower** [spliit-app/spliit#229]
It seems that with the new 1.10.0 release, expenses may be broken in the fact that they are all being multiplied by 100. For example if I put $0.02 and hit submit, it then shows as $2.00. 

![Screenshot_20240928-212436.png](https://github.com/user-attachments/assets/fa37950d-bcd5-46f9-a46a-d92be806eb62)

![Screenshot_20240928-212503.png](https://github.com/user-attachments/assets/7cdaef53-48d6-46e1-8a4b-bc5c7d66a1c7)

**Comment by tigressine** [comment]
Happening to me as well. Perhaps related to this recent commit:

https://github.com/spliit-app/spliit/commit/9a5674e2399494c38b6342eeaca7cd8716b0c495#diff-da10bcc7d8dff796f50c9358a7268eb5abd2c50f460aecc4b2be1c691a966224

`src/lib/utils.ts` line 43
```
-  const formattedAmount = format.format(amount / 100)
+  const formattedAmount = format.format(amount)
```

Looks like this formatting code used to divide by 100 and recently was changed to not do that.

@mertd Do you recall why you changed this in your PR?

**Comment by finnolin** [comment]
same on the official instance. my gf just asked me why I put down 200.000 yen for our coffee this morning...

**Comment by mertd** [comment]
The idea was to let the formatter actually do all of the formatting, and to fix the amount in the preview for scanned receipts. Seems like that broke amounts elsewhere. I guess there is some multiplication happening in the component then, considering the new tests for the formatter succeed?

**Comment by okainov** [comment]
Same here, existing groups are ruined

**Comment by client-side96** [comment]
I think that this issue seems more problematic than it actually is. The stored amount in database seem to be still correct. Eg. If I go into a transaction, the number input values are still correct. So the only thing that needs to be adjusted is the formatting of the currencies.

**Comment by mertd** [comment]
> Would it make sense to pass a factor (default value would be 0.01) to `formatCurrency` and alter the factor in the places where we do not need to divide by a 100? @mertd

Good idea, I did something similar and added a boolean switch in the PR linked above in case division is not necessary (currently only for the AI receipt preview). The added documentation hopefully helps avoiding this bug in the future.
