### ISSUE TITLE
Amounts on Overview Screen Are 100 times the Actual Values

### ISSUE THREAD

**Issue by EnablSiteAdmin** [spliit-app/spliit#230]
Description:

When navigating to the overview screen, all amounts displayed are 100 times the actual values they should be. This affects all monetary figures shown on the screen.

For example, if an amount is supposed to be €100, the screen displays €10,000 instead.

Steps to Reproduce:

Navigate to the overview screen.
Observe the amounts displayed on the screen.

Expected Behavior: Amounts should reflect the correct values in euros.

Actual Behavior: All amounts displayed are 10 times the actual value.

**Comment by scastiel** [comment]
Fixed in #231. Thanks @EnablSiteAdmin for the bug report :)

**Comment by EnablSiteAdmin** [comment]
Thx for the fix !
