### ISSUE TITLE
Paginate expenses

### ISSUE THREAD

**Issue by scastiel** [spliit-app/spliit#30]
The expense list can be slow when displaying several hundreds of transactions. It would make sense to paginate transactions, i.e. either:

1. Display the first X transactions by default, and then a “Show more” button
2. Display an actual pagination, i.e. show page one by default and offer the option to go to a random page.

My preference is on option 1, but open to discussion.

**Comment by justcallmelarry** [comment]
I'll add that i like option 1 as well. As long as you can search and export I don't think you really need option 2.

**Comment by manuerwin** [comment]
Agree, option 1 would work for me so long as search works well

**Comment by shynst** [comment]
I would prefer a technique called "infinite scroll" over traditional "old-school" pagination.

**Infinite Scroll** is a technique that automatically adds the next page as the user scrolls down through content, more content is loaded. User don’t need to wait for pages to preload. So infinite scroll can provide user a better experience.

https://blog.logrocket.com/3-ways-implement-infinite-scroll-react/

**Comment by manuerwin** [comment]
> I would prefer a technique called "infinite scroll" over traditional "old-school" pagination.
> Infinite Scroll is a technique that automatically adds the next page as the user scrolls down through content, more content is loaded. User don’t need to wait for pages to preload. So infinite scroll can provide user a better experience.

I change my vote to this "Option 3" :)

**Comment by shynst** [comment]
Here is my implementation of "option 3: infinite scroll": #95

**Comment by ChristopherJohnston** [comment]
@scastiel I think this can now be closed after the #95 merge
