### ISSUE TITLE
RFC: Optimize Spliit for self-hosting

### ISSUE THREAD

**Issue by scastiel** [spliit-app/spliit#47]
As Spliit is open source, I think it would be nice if it was easy to deploy it anywhere easily.

This means:
- Having a bit of documentation to explain the steps to follow.
- Put all the _branding_ content out of this repo (landing page, footer…) to offer a more neutral application by default.

Curious to know if anyone has this need or suggestions about implementation. Feel free to give your two cents here 😉

**Comment by manuerwin** [comment]
It would be nice to self-host (plus would decrease your costs !)

I'd be very happy to keep the branding IN the repo :)
