### ISSUE TITLE
Search for expenses

### ISSUE THREAD

**Issue by ankitbahl** [spliit-app/spliit#51]
I personally need to look for old expenses often. One of the annoyingly premium features of Splitwise is searching for expenses - it would be nice to have some sort of search on the expenses list page.

**Comment by manuerwin** [comment]
Is that only in the current group or across multiple groups?

**Comment by scastiel** [comment]
Assuming only for one group, that shouldn’t be too hard to implement, as all the expenses already are available client-side. (Might be a bit more complex when #30 is implemented).

**Comment by scastiel** [comment]
Thanks @ankitbahl for implementing the feature ❤️
