### ISSUE TITLE
Default participants and split

### ISSUE THREAD

**Issue by mertd** [spliit-app/spliit#58]
With the current defaults (no participant checked), at least one interaction with the participant list is necessary to be able to save an expense. I have to "select all" participants almost every time. 

Considering there is no use case where saving without any interactions is possible, having the expense split evenly across all group members may be a better default.

**Comment by mertd** [comment]
I wrote a quick draft of what I imagined in #59. So far I am just assuming that "split evenly with everyone" is the most common use case, without any discussions or metrics to base my assumption on, so I am keen to hear your opinions.

**Comment by justcallmelarry** [comment]
I also thought of this. My main group is with 1 other person, so we are definitely always choosing to split for both.

I, being a self proclaimed coward, was thinking that I would open an issue with a toggle on group level wether to add all or none by default, so it's switchable by group

But my guess is that you would rather have the default being all chosen over none, as well.

**Comment by mertd** [comment]
Great to hear that my first suggestion (small as it may be) is received so positively!

> I would open an issue with a toggle on group level wether to add all or none by default, so it's switchable by group

That was an option I had in mind as well, but I thought it was better to start out with a simpler approach unless we know there is demand for a more sophisticated solution.
