### ISSUE TITLE
Bug: Image paths are too non-unique

### ISSUE THREAD

**Issue by justcallmelarry** [spliit-app/spliit#68]
## Description
I was looking into if I could get minio working over s3 locally without too many issues (I couldn't, but I'll leave that for another time).

I did notice however that the path is just the filename as root in the bucket, which will start causing issues. I have already done some rudimentary tests and found that images do overwrite each other if they share the same name between expenses, and I believe that it also does between groups.

###  Steps to reproduce:
1. Create an expense, add the image `image.jpg` to it.
2. Look in the S3 bucket, you will see that `image.jpg` is in the root, so far so good.
3. Add another expense to the group, add (preferably another) image called `image.jpg` to it
4. Notice that there is only one image in the S3 bucket, named `image.jpg`.
5. Do the same for a different expense in a different group, still only the one image left.

This is generally not great, as you might end up seeing the images belonging to someone else, and may have your own images overwritten as well.

### Suggestion for solving the issue
I have a few suggestions on how to solve the issue, any or all might be used to alleviate the problem:
* [ ] Add the group ID as a path prefix (example: `NEFJA5--IBHFY3L99D0r4/image.jpg`)
* [ ] Use the ID of the image when uploading it to s3, storing the name in the table instead so that it can be shown in frontend if wanted/needed. This should allow it to be unique, otherwise I guess  the database will run into issues
* [ ] Add a timestamp (down to milliseconds) or other uniqueness as a prefix/suffix to the image (`2024-01-29T19:48:39.961269--image.jpg` / `image--809ee38c-6da7-44c2-a34d-54a6802c658a.jpg`

I would generally recommend the prefix of group_id, and also just renaming the image to the image ID.
This will allow you to not run into weird issues with filenames (unsure what they might be, but I guess you could use weird chars in filenames that cause issues somehow) but also easily remove all images of a group if it is deleted, both manually and via the CLI/API, even if you lose access to the database somehow.
This will also allow image paths not to be in risk of colliding.

EDIT: I see now that there was an update while I was testing :) will close this issue

**Comment by scastiel** [comment]
Indeed, I noticed this bug this morning and fixed it right away :)
