### ISSUE TITLE
Simplify Debts Function

### ISSUE THREAD

**Issue by vladartym** [spliit-app/spliit#70]
Can we add the "simplify debts" function that splitwise has?

The way it works is if Bob owes Jack $10 and Jack owes Anna $10. 

When simplify debts is toggled on, then we can simplify the debts where Bob just owes Anna $10. Pretty prime function that splitwise has. 

Let me know if we need some UX work for this. Otherwise we just copy what splitwise has done 😊

**Comment by scastiel** [comment]
The suggested reimbursements already work that way if I understand what you’re suggesting. [See this example group I just created](https://spliit.app/groups/V1J_p9t6c9IXHqciG4vIB/expenses).
