### ISSUE TITLE
Translations of the website

### ISSUE THREAD

**Issue by acress1** [spliit-app/spliit#75]
Hi,

not an issue, but is there an available way to contribute to translate the website in other languages ? I'm French and I'd love to contribute to get the website in a French translation :)
Thanks,
cress

**Comment by scastiel** [comment]
I know that at some point I’ll have to offer Spliit in several languages. Until we set up the app internationalization, it is not possible to contribute to translation. Hopefully soon :)

**Comment by mlainz** [comment]
I could also help you with an Spanish translation whenever you set up internationalization.

**Comment by vanako** [comment]
Can do German, Japanese, Malaysian when you set up the feature and need help :blush:

**Comment by bnjbvr** [comment]
Happy to help with the French translation too.

In terms of setting up i10n, do you have a preferred framework/tooling in mind?

**Comment by scastiel** [comment]
@bnjbvr 

> In terms of setting up i10n, do you have a preferred framework/tooling in mind?

Not really. I would prefer staying as close as possible to [what is suggested by Next.js’ documentation](https://nextjs.org/docs/app/building-your-application/routing/internationalization).

**Comment by jp-clerc** [comment]
Hi! I can help for the french translation !

**Comment by pktiuk** [comment]
After setting up multiple languages you could integrate this repository with [weblate](https://weblate.org), which allows easy translating for community (and is well integrated with Git)

**Comment by Strekol** [comment]
> Hi,
> 
> not an issue, but is there an available way to contribute to translate the website in other languages ? I'm French and I'd love to contribute to get the website in a French translation :) Thanks, cress

Hello,
I made a PR based on the fork of iqqmuT with french translation :)
Feel free to contribute [here](https://github.com/iqqmuT/spliit/pull/1)

**Comment by scastiel** [comment]
Hey @Strekol would you mind submitting a PR in this repo with the French translation? 😉

**Comment by scastiel** [comment]
Closing as implemented in #181. Thanks a lot @iqqmuT, thanks to you we can start adding translations to many languages ❤️
