### ISSUE TITLE
Decimal separator for locales where decimal point is a comma

### ISSUE THREAD

**Issue by scastiel** [spliit-app/spliit#78]
> Unfortunately, the "amount" entry field only allows a dot ( . ) as decimal separator, not a comma ( , ). This is not a problem on desktop computers with a keyboard, however on iPhone with german keyboard layout, I am presented with a keyboard containing 0-9 and the comma only (due to the input field type I guess). I have no possibility to enter a dot instead of a comma, and therefore cannot add an expense. I hope you're able to fix that, that would be awesome!

**Comment by scastiel** [comment]
Stilly trying to reproduce. Getting more information about the bug.

**Comment by justcallmelarry** [comment]
I can reproduce this on my phone, and am available to help out with testing if you wish
I tried looking into this myself, but to no avail 😅
