### ISSUE TITLE
Resize large images to conserve storage

### ISSUE THREAD

**Issue by manuerwin** [spliit-app/spliit#83]
The app currently seems to allow any size image to be uploaded (I was able to upload a 35MB sample image see #84).
Suggest automatically resize large attached images (to 1920p max?) to conserve storage space.

**Comment by scastiel** [comment]
Assuming we can limit the upload file size, I don’t think it is worth resizing the images, at least for the S3 upload.

**Comment by justcallmelarry** [comment]
> Was just thinking that cameras often take large images where smaller resolution one would likely suffice for viewing. For example, imagine all 20,000 existing expenses had a 1MB image => 20,000MB => 20GB Auto-resizing to a max resolution “should” conserve storage in the long term I think?

Just adding a comment that you can achieve this type of functionality by running a lambda that resizes images for you (based on S3 events or MinIO equivalent), without it having to be a part of the app.

Unless I'm mistaken, it seems like the images never pass the backend with the current solution, so adding some sort of resizing is not a minor change.

**Comment by manuerwin** [comment]
I like this approach @justcallmelarry, thanks for the input :)
