### ISSUE TITLE
Tag version on merge to main

### ISSUE THREAD

**Issue by ChristopherJohnston** [spliit-app/spliit#86]
@scastiel is it possible to add a tag to the merge commit whenever merging a new feature into main (either automatically or manually)? Perhaps with an uptick on the version number in package.json?

I'd like to be able to download the repo as of a specific point in a home-assistant add-on implementation (see #56) to ensure consistency of deployments.

**Comment by manuerwin** [comment]
Agree.
Also it would be great to start incrementing version in package.json given there's a lot of change :)
Thinking that some functions (e.g. export) would benefit from being able to include version # in them to help with future function compatibility (e.g. import).

**Comment by scastiel** [comment]
I just created the first release (1.0.0). I’ll keep it as a manual process for now, but I’ll try to create a new release each time there is a major change :)

**Comment by ChristopherJohnston** [comment]
Thanks, this works well for building the images used by my [homeassistant add-on](https://github.com/ChristopherJohnston/spliit-app-homeassistant-addons) implementation.
