### ISSUE TITLE
Cancel button on add expense page

### ISSUE THREAD

**Issue by linw0724** [spliit-app/spliit#92]
Would it be possible to add a "Cancel" button at the bottom the add expense page that takes you to the page you were previously? Instead of having to click to another tab then back to "expense" tab to cancel?

**Comment by justcallmelarry** [comment]
> Would it be possible to add a "Cancel" button at the bottom the add expense page that takes you to the page you were previously? Instead of having to click to another tab then back to "expense" tab to cancel?

You can also click the name of the group to get back to the expense list 😄 
But yeah, I also found this mildly confusing before I figured that out, so I do think it's a nice suggestion!
