### ISSUE TITLE
Feature request: group spending tab similar to splitwise

### ISSUE THREAD

**Issue by meta-boy** [spliit-app/spliit#93]
I have written my own script to calculate this from the json dump that spliit generates. But would be very useful if the same is shown on the UI itself
ref: 
<img src="https://github.com/spliit-app/spliit/assets/42678386/1d0fb4a1-c3e6-45f4-9b1d-3ebf699bfab9" width="200">

**Comment by meta-boy** [comment]
if this is accepted as a feature request then I can pick this up. Might be a little slow to work since I'm not very familiar with frontends but would like to take a dab at it :)

**Comment by guysoft** [comment]
A feature that I am missing here is monthly spending total. The dropdown that is there is not implemented - should I open a separate issue for that?
