### ISSUE TITLE
Feature idea: save split mode for future expenses

### ISSUE THREAD

**Issue by jantuomi** [spliit-app/spliit#98]
### Use case

I use Spliit with my SO for splitting, among others, household expenses. We have a system where one person pays a larger percentage nearly every time. The "Split mode – By percentage" is great for this. However, toggling the mode and typing in the correct percentages requires a total of 12 clicks or button presses (focusing the inputs, typing the numbers). This gets kind of annoying.

As a user I would like to save my default split mode, so that when opening the expense form, the saved split mode and numeric values would get pre-filled.

### Design

A quick design idea:
![image](https://github.com/spliit-app/spliit/assets/5064726/a15ada34-b3c6-4c8e-9e34-2b5206622c1e)

The checkbox would only appear if the mode is changed from its (current) default, in order to avoid cluttering the form.

The text could read:
- Set as default split mode (implying a cross-group setting)
- Set as default split mode **for this group** (implying that the setting only affects this group)
- Set as **my** default split mode (implying that the setting only affects me)
- Set as default **split options** (implying that in addition to the split mode, also the numeric values as stored)

or some combination/variation of these.

### Implementation

Some settings are already being stored in local storage, using a compound key of `<groupId>--<someFieldKey>`. I think this method could be used for this as well.

I can do the implementation myself 👍 Comments on the idea, especially the design, are more than welcome.

**Comment by justcallmelarry** [comment]
I think it makes sense to store it in localStorage, but have no good copy suggestion to make sure that everyone know it's not for all devices etc. Maybe something like "my default split mode for this device" or something would work?

I don't think it makes sense to have someone change the default split mode and then everyones settings will change.

I am wondering what would happen in this case if someone is added to or removed from the group?

**Comment by jantuomi** [comment]
Yeah, having the setting affect everyone would be pretty tricky. I think a straightforward only-me, only-this-device setting would be best. It's not a big deal to set it up on each device you use anyway.

I'll have a go at implementing this.

**Comment by ChristopherJohnston** [comment]
I think this is now closed with the latest release
